[package]
name = "fractal_explorer"
version = "0.1.0"
authors = ["Shishir Tandale <shishir.tandale@homegrown-solutions.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.5.1"
rug = "1.12"